language: python
python:
  - "3.4"

cache:
  directories:
    - pip_download_cache

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE

script:
  - tox -e $TOX_ENV

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - TOX_ENV=py33-django1.5
    - TOX_ENV=py33-django1.6
    - TOX_ENV=py33-django1.7
    - TOX_ENV=py34-django1.5
    - TOX_ENV=py34-django1.6
    - TOX_ENV=py34-django1.7

notifications:
  email: true
